title: Nikolai Pismennyi
author:
  name: Nikolai Pismennyi
  email: npismenniy@gmail.com

description: >
  Personal website

remote_theme: jekyll/minima
#theme: minima

header_pages:
  - index.md


minima:
  skin: auto
  social_links:
    - { platform: linkedin,  user_url: "https://www.linkedin.com/in/nikolai-pismennyi/" }
    - { platform: github,  user_url: "https://github.com/kapis" }