theme: minima

minima:
  skin: auto
  social_links:
    - { platform: linkedin,  user_url: "https://www.linkedin.com/in/nikolai-pismennyi/" }
    - { platform: github,  user_url: "https://github.com/kapis" }