theme: minima

header_pages:
  - index.md

site.title: "Nikolai Pismennyi"

author:
  name: "Nikolai Pismennyi"
  #email: "john.smith@foobar.com"


minima:
  skin: auto
  social_links:
    - { platform: linkedin,  user_url: "https://www.linkedin.com/in/nikolai-pismennyi/" }
    - { platform: github,  user_url: "https://github.com/kapis" }